#!/usr/bin/env bash

../bin/l2evaluate core-meta.l2 64-numbers-meta.l2 text-meta.l2 flow-meta.l2 list-meta.l2 ../bin/x86_64.o x86-64-linux-interface-meta.l2 lexer-meta.l2 elf-meta.l2 x86-64-object-meta.l2 expressions-meta.l2 x86-64-assembler-meta.l2 x86-64-generator-meta.l2 - x86-64-linux-interface.l2 lexer.l2 x86-64-object.l2 expressions.l2 x86-64-assembler.l2 preparer.l2 x86-64-generator.l2 evaluate.l2 list.l2 64-numbers.l2

echo $'.globl x8664linuxinterfaceo\n.text\nx8664linuxinterfaceo:\n' > "x86-64-linux-interface.s"

echo $'.globl lexero\n.text\nlexero:\n' > "lexer.s"

echo $'.globl x8664objecto\n.text\nx8664objecto:\n' > "x86-64-object.s"

echo $'.globl expressionso\n.text\nexpressionso:\n' > "expressions.s"

echo $'.globl x8664assemblero\n.text\nx8664assemblero:\n' > "x86-64-assembler.s"

echo $'.globl preparero\n.text\npreparero:\n' > "preparer.s"

echo $'.globl x8664generatoro\n.text\nx8664generatoro:\n' > "x86-64-generator.s"

echo $'.globl evaluateo\n.text\nevaluateo:\n' > "evaluate.s"

echo $'.globl listo\n.text\nlisto:\n' > "list.s"

echo $'.globl numbers64o\n.text\nnumbers64o:\n' > "64-numbers.s"

echo $'.globl _start\n.text\n_start:\ncall x8664linuxinterfaceo\ncall lexero\ncall x8664objecto\ncall expressionso\ncall x8664assemblero\ncall preparero\ncall x8664generatoro\ncall evaluateo\ncall listo\ncall numbers64o\n' > "start.s"

gcc -nostdlib x86-64-linux-interface.s x86-64-linux-interface.o lexer.s lexer.o x86-64-object.s x86-64-object.o expressions.s expressions.o x86-64-assembler.s x86-64-assembler.o preparer.s preparer.o x86-64-generator.s x86-64-generator.o evaluate.s evaluate.o list.s list.o 64-numbers.s 64-numbers.o ../bin/x86_64.o start.s -o bootstrapped_l2compile

rm "x86-64-linux-interface.s" "lexer.s" "x86-64-object.s" "expressions.s" "x86-64-assembler.s" "preparer.s" "x86-64-generator.s" "evaluate.s" "list.s" "64-numbers.s" "x86-64-linux-interface.o" "lexer.o" "x86-64-object.o" "expressions.o" "x86-64-assembler.o" "preparer.o" "x86-64-generator.o" "evaluate.o" "list.o" "64-numbers.o" "start.s"
