#!/usr/bin/env bash
mkdir -p bin

echo "* Compiling assembly support routines ..."
gcc -nostdlib -static -g -fno-stack-protector -c -o bin/x86_64_linux_interface.o bootstrap/x86_64_linux_interface.s
echo "* Compiling the bootstrap compiler ..."
gcc -mabi=ms -nostdlib -static -g -fno-stack-protector -o bin/l2compile bootstrap/compile.c bin/x86_64_linux_interface.o

