#!/usr/bin/env bash
mkdir -p bin

musl-gcc --static -g -c -o bin/x86_64_linux_interface.o src/x86_64_linux_interface.s

musl-gcc --static -g -c -o bin/l2compile.o src/compile.c
objcopy --redefine-syms=assets/l2_sym_pairs bin/l2compile.o
ar rcs bin/l2compile.a bin/l2compile.o bin/x86_64_linux_interface.o
rm bin/l2compile.o

musl-gcc --static -g -c -o bin/l2evaluate.o src/evaluate.c
objcopy --redefine-syms=assets/l2_sym_pairs bin/l2evaluate.o
musl-gcc -g -o bin/l2evaluate bin/l2evaluate.o bin/x86_64_linux_interface.o
rm bin/l2evaluate.o

musl-gcc --static -g -c -o bin/x86_64.o assets/x86_64.s
objcopy --redefine-syms=assets/x86_64_sym_pairs bin/x86_64.o
