#!/usr/bin/env bash
mkdir bin
gcc -m32 -g -c -o bin/l2compile.o src/l2.c
objcopy --redefine-syms=assets/l2_sym_pairs bin/l2compile.o
gcc -m32 -g -ldl -Wl,--export-dynamic -o bin/l2compile bin/l2compile.o
rm bin/l2compile.o
gcc -m32 -g -c -o bin/demort.o assets/demort.s
objcopy --redefine-syms=assets/demort_sym_pairs bin/demort.o
