#!/usr/bin/env bash

cd ./src

echo "* Compiling the instruction wrappers that provide x86-64 functionality ..."

gcc --static -g -c -o ../bin/x86_64.o x86_64.s

objcopy --redefine-syms=x86_64_sym_pairs ../bin/x86_64.o

echo "* Compiling L2 source code into object files ..."

../bin/l2compile core-meta.l2 text-meta.l2 flow-meta.l2 elf-meta.l2 x86-64-linux-interface.l2 lexer.l2 x86-64-object.l2 expressions.l2 x86-64-assembler.l2 preparer.l2 x86-64-generator.l2 compile.l2 list.l2 64-numbers.l2 arithmetic-intrinsics.l2 - arithmetic - ../bin/x86_64.o

echo "* Writing out labels for object files ..."

echo $'.globl x8664linuxinterfaceo\n.text\nx8664linuxinterfaceo:\n' > "x86-64-linux-interface.s"

echo $'.globl lexero\n.text\nlexero:\n' > "lexer.s"

echo $'.globl x8664objecto\n.text\nx8664objecto:\n' > "x86-64-object.s"

echo $'.globl expressionso\n.text\nexpressionso:\n' > "expressions.s"

echo $'.globl x8664assemblero\n.text\nx8664assemblero:\n' > "x86-64-assembler.s"

echo $'.globl preparero\n.text\npreparero:\n' > "preparer.s"

echo $'.globl x8664generatoro\n.text\nx8664generatoro:\n' > "x86-64-generator.s"

echo $'.globl arithmeticintrinsicso\n.text\narithmeticintrinsicso:\n' > "arithmetic-intrinsics.s"

echo $'.globl compileo\n.text\ncompileo:\n' > "compile.s"

echo $'.globl listo\n.text\nlisto:\n' > "list.s"

echo $'.globl numbers64o\n.text\nnumbers64o:\n' > "64-numbers.s"

echo "* Writing out some assembly to call each initializer one by one"

echo $'.globl _start\n.text\n_start:\ncall x8664linuxinterfaceo\ncall lexero\ncall x8664objecto\ncall expressionso\ncall x8664assemblero\ncall preparero\ncall x8664generatoro\ncall listo\ncall numbers64o\ncall arithmeticintrinsicso\ncall compileo\n' > "start.s"

echo "* Linking the produced object files together and replacing l2compile ..."

gcc -fuse-ld=gold -static -nostdlib -Wl,--unresolved-symbols=ignore-in-object-files x86-64-linux-interface.s x86-64-linux-interface.l2.o lexer.s lexer.l2.o x86-64-object.s x86-64-object.l2.o expressions.s expressions.l2.o x86-64-assembler.s x86-64-assembler.l2.o preparer.s preparer.l2.o x86-64-generator.s x86-64-generator.l2.o arithmetic-intrinsics.s arithmetic-intrinsics.l2.o compile.s compile.l2.o list.s list.l2.o 64-numbers.s 64-numbers.l2.o ../bin/x86_64.o start.s -o ../bin/l2compile

echo "* Removing the intermediate files ..."

rm "arithmetic.o" "x86-64-linux-interface.s" "lexer.s" "x86-64-object.s" "expressions.s" "x86-64-assembler.s" "preparer.s" "x86-64-generator.s" "arithmetic-intrinsics.s" "compile.s" "list.s" "64-numbers.s" "x86-64-linux-interface.l2.o" "lexer.l2.o" "x86-64-object.l2.o" "expressions.l2.o" "x86-64-assembler.l2.o" "preparer.l2.o" "x86-64-generator.l2.o" "arithmetic-intrinsics.l2.o" "compile.l2.o" "list.l2.o" "64-numbers.l2.o" "elf-meta.l2.o" "flow-meta.l2.o" "text-meta.l2.o" "core-meta.l2.o" "start.s"

