#!/usr/bin/env bash

cd ./src

echo "* Compiling the instruction wrappers that provide x86-64 functionality ..."

gcc --static -g -c -o ../bin/x86_64.o x86_64.s

objcopy --redefine-syms=x86_64_sym_pairs ../bin/x86_64.o

echo "* Compiling L2 source code into object files ..."

gdb --args ../bin/l2compile core-meta.l2 text-meta.l2 flow-meta.l2 elf-meta.l2 x86-64-linux-interface.l2 lexer.l2 x86-64-object.l2 expressions.l2 x86-64-assembler.l2 analysis.l2 x86-64-generator.l2 compile.l2 list.l2 64-numbers.l2 x86-64-arithmetic-intrinsics.l2 - arithmetic - ../bin/x86_64.o

echo "* Linking the produced object files together and replacing l2compile ..."

gcc -fuse-ld=gold -static -nostdlib -Wl,--unresolved-symbols=ignore-in-object-files x86-64-linux-interface.l2.o lexer.l2.o x86-64-object.l2.o expressions.l2.o x86-64-assembler.l2.o analysis.l2.o x86-64-generator.l2.o x86-64-arithmetic-intrinsics.l2.o compile.l2.o list.l2.o 64-numbers.l2.o ../bin/x86_64.o --entry=0x000000000040010c -Ttext=0x0000000000400000  -o ../bin/l2compile

echo "* Removing the intermediate files ..."

rm "arithmetic.o" "x86-64-linux-interface.l2.o" "lexer.l2.o" "x86-64-object.l2.o" "expressions.l2.o" "x86-64-assembler.l2.o" "analysis.l2.o" "x86-64-generator.l2.o" "x86-64-arithmetic-intrinsics.l2.o" "compile.l2.o" "list.l2.o" "64-numbers.l2.o" "elf-meta.l2.o" "flow-meta.l2.o" "text-meta.l2.o" "core-meta.l2.o"

